# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "Raymond Camden"

# A description of your site for social meta tag, search engines, and feed.xml
description: "DevRel at large, Star Wars nerd, Web/Serverless hacker, lover of good beer and good books. Oh, and cats."

# Tagline near the site title
tagline: "Code, cats, Star Wars, and more cats"

# The subpath of your site, e.g. /blog, for generating urls
baseurl: 

exclude: [_posts/2003,_posts/2004,_posts/2005,_posts/2006,_posts/2007,_posts/2008,_posts/2009,_posts/2010,_posts/2011,_posts/2012,_posts/2013,_posts/2014,_posts/2015,_posts/2016,_posts/2017,_posts/2018/01,_posts/2018/02,_posts/2018/03,_posts/2018/04,node_modules]

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "https://www.raymondcamden.com"

include: [_redirects]

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About
  url: /about/
- text: Speaking
  url: /speaking/
- text: Contact
  url: /contact/
- text: Search
  url: /search/

# The shortname for your Disqus site to enable comments.
disqus: 

# Author information - author info at the bottom of the post
author_name: "Raymond Camden"
author_bio: "Raymond is a developer advocate. He focuses on JavaScript, serverless and enterprise cat demos."
author_url:  "https://www.raymondcamden.com"
author_location: "Lafayette, LA"
author_image: /images/avatar.jpg

# Sidebar Add banner
banner_url: "http://justgoodthemes.com"
banner_image: images/banner.jpg

# Sidebar newsletter widget - add your form action url for MailChimp signup form here
mailchimp_url: "//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117"

# Social links in the site footer
twitter_username: "raymondcamden"
#facebook_username: "username"
googleplus_username: "+raymondcamden"
github_username: "cfjedimaster"
codepen_username: "cfjedimaster"
#dribbble_uername: "username"
medium_username: "@cfjedimaster"
#instagram_username: "username"
#pinterest_username: "username"
linkedin_username: "raymondcamden"
#weibo_username: "username"
youtube_username: "theraymondcamden"

# http://jekyllrb.com/docs/pagination/
#paginate: 10
#paginate_path: '/blog/page:num/'
#plugins: [jekyll-paginate]

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false
